tasks:
  - name: npm init
    init: |
      npm install
      npm run build
    command: npm run dev
  - name: vscode settings
    init: |
      mkdir -p "$PWD/.vscode";
      cat << 'EOF' > "$PWD/.vscode/settings.json"
      {
        "files.associations": {
            "*.njk": "html"
        }
      }
      EOF
      exit

ports:
  - port: 8080
    onOpen: open-browser
  - port: 3001
    onOpen: ignore

vscode:
  extensions:
    - ecmel.vscode-html-css
  