tasks:
  - name: npm init
    init: |
      npm install
      npm run build
    command: npm run dev
  - name: vscode settings
    init: |
      mkdir -p "$PWD/.vscode";
      cat << 'EOF' > "$PWD/.vscode/settings.json"
      {
        "files.associations": {
            "*.njk": "html"
        },
        "window.zoomLevel": 1
      }
      EOF
      exit
  - name: work terminal
    command: echo "Hello 👋"
    openMode: split-right

ports:
  - port: 8080
    onOpen: open-browser
  - port: 3001
    onOpen: ignore

vscode:
  extensions:
    - ecmel.vscode-html-css
  
gitConfig:
  alias.st: status
  alias.l: log --graph --pretty=default
  alias.lola: log --graph --oneline --all
  alias.fp: fetch --prune
